# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

#pid_file /run/mosquitto/mosquitto.pid
password_file /etc/mosquitto/pwfile
allow_anonymous true

persistence true
persistence_location /var/lib/mosquitto/

listener 1883 0.0.0.0
#bind_address *

log_dest file /var/log/mosquitto/mosquitto.log
#log_type debug

include_dir /etc/mosquitto/conf.d

max_inflight_messages 32768
