#!/usr/bin/env python3
"""Creates an XMQ extension project that builds and loads before a line of it is written.

An extension is a shared library the broker opens at start-up. It sees one header - the C ABI in
extension/xmq_extension.h - and links nothing of the broker, which is what lets it be built with
another compiler, kept closed, and shipped on its own schedule.

What this writes is a project with all of that already arranged: the CMake, the class, the entry
point, the configuration entry to paste, and a README. Every place where a decision belongs to you
is marked TODO and says what the choice is between. Build it as it comes out and the broker will
load it and log that it did - then start replacing the TODOs.

    ./new-extension.py audit-trail --capability observer
    ./new-extension.py device-auth --capability authenticator --database
    ./new-extension.py site-acl --capability authorizer --capability observer

Run with --help for the rest.
"""

import argparse
import pathlib
import re
import sys

CAPABILITIES = {
    "observer": "XMQ_CAP_OBSERVER",
    "authenticator": "XMQ_CAP_AUTHENTICATOR",
    "authorizer": "XMQ_CAP_AUTHORIZER",
}


def class_name(name):
    """audit-trail -> AuditTrail."""
    return "".join(part.capitalize() for part in re.split(r"[-_\s]+", name) if part)


def identifier(name):
    """audit-trail -> audit_trail, for file and target names."""
    return re.sub(r"[-\s]+", "_", name)


def check_name(name):
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_-]*", name):
        raise SystemExit(
            "The name must start with a letter and hold only letters, digits, '-' and '_': "
            "it becomes a C++ class, a CMake target and the name the broker matches. Got: " + name)


# ─────────────────────────────────────────────────────────────────────────────
# The generated C++, in pieces. Each capability brings its own methods and the
# comments that say what the answers mean, because that is where the mistakes are.
# ─────────────────────────────────────────────────────────────────────────────

CPP_HEADER = '''/**
 * @file @@CLASS@@.cpp
 * @brief @@NAME@@ - an XMQ extension.
 *
 * Generated by new-extension.py. The TODOs are the parts that are yours; everything around them is
 * already right and can be left alone.
 *
 * Two rules that matter more than anything else here:
 *
 *  - **Nothing of the broker may be included or linked.** The C ABI is the whole contract. That is
 *    what lets this be built with a different compiler and a different standard library from the
 *    broker's, and why it keeps working when the broker is upgraded under it.
 *  - **The capability list in XMQ_DEFINE_EXTENSION is a declaration, not a description.** Declare
 *    only what this does. With a capability undeclared the broker never builds the machinery behind
 *    it - no event thread, no authentication pool - and the paths it would sit on keep their
 *    original shape.
 */

#include <extension/XmqExtension.h>
@@EXTRA_INCLUDES@@
#include <string>

namespace {

class @@CLASS@@ : public xmq::XmqExtensionBase
{
public:
    using XmqExtensionBase::XmqExtensionBase;

    /**
     * @brief Called once, before the broker serves anything.
     *
     * Everything expensive belongs here: connections, files, threads of your own. Returning false
     * unloads the extension; the broker still starts, unless this entry is marked 'required' in
     * xmq_extensions.conf, and then it will not serve MQTT until this starts.
     *
     * Refusing to start beats running broken. An extension that cannot do its job but answers
     * anyway looks exactly like one that works.
     */
    bool start() override
    {
        // Settings come from this extension's own block in xmq_extensions.conf and mean whatever
        // your documentation says they mean. An absent one reads as empty.
        const auto example = setting("example");
@@START_ATTRIBUTES@@@@START_BODY@@
@@SKELETON_WARNING@@
        log(XMQ_LOG_INFO, "started" + (example.empty() ? std::string() : ", example=" + example));
        return true;
    }

    /**
     * @brief Called once, as the broker stops. Nothing else is called after it.
     */
    bool stop() override
    {
@@STOP_BODY@@
        log(XMQ_LOG_INFO, "stopped");
        return true;
    }
'''

OBSERVER_START_ATTRIBUTES = '''
        // Facts about an event that are not fields of xmq_event travel by name. Ask here and
        // nowhere else: values are captured as the event is queued, on the broker's message
        // threads, so asking later cannot reach back for what was never taken - and only what is
        // asked for is captured, so a name nobody wants costs the broker nothing.
        //
        // This is also how an extension survives broker versions. A name this broker does not
        // publish comes back empty rather than failing, and a broker that later learns to publish
        // more names needs no new ABI and no rebuild of this.
        //
        // TODO: ask for what you need, or delete this if you need nothing beyond the fields.
        wantEventAttributes("remote_address");
'''

DECIDER_WARNING = '''
        // TODO: delete this line once the decisions below are written.
        //
        // Until then this extension loads, runs, and changes nothing: every decision below answers
        // NOT_HANDLED, which means "I have no opinion" - the broker asks the next extension and
        // then decides for itself, exactly as it would with this extension absent. That is the only
        // safe thing for a skeleton to do, and it is indistinguishable from working, so it says so
        // rather than leaving you to find out from a client that connects when it should not.
        log(XMQ_LOG_WARNING, "@@NAME@@ is a generated skeleton: it does not decide anything yet");
'''

OBSERVER_WARNING = '''
        // TODO: delete this line once onEvent() does something.
        //
        // Until then this extension loads and receives every event the broker raises, and does
        // nothing with any of them. That is the only safe thing for a skeleton to do, and from
        // outside it is indistinguishable from an observer that works, so it says so.
        log(XMQ_LOG_WARNING, "@@NAME@@ is a generated skeleton: it watches but records nothing");
'''

CPP_OBSERVER = '''
    /**
     * @brief One thing that happened in the broker.
     *
     * Runs on a thread the host keeps for this, fed by a bounded queue that the broker's reactor,
     * receive and send workers only ever push to. So taking your time here is allowed - what you
     * must not do is make the broker wait. When the queue fills, events are dropped and counted:
     * slow is lossy, never fatal.
     *
     * The strings belong to the broker and last only for this call. Copy anything you keep.
     */
    void onEvent(const xmq_event& event) override
    {
        const auto clientId = std::string(xmq::view(event.client_id));
        const auto username = std::string(xmq::view(event.username));
        const auto topic = std::string(xmq::view(event.topic));

        // Asked for in start(). Empty when the name was not requested, does not apply to this event
        // - a publish has no address - or is one this broker does not publish. All three read the
        // same way on purpose: a fact that is not there is not an error.
        const auto address = eventAttribute(event, "remote_address");

        switch (xmq::eventType(event))
        {
            case XMQ_EVENT_CLIENT_CONNECTED:
                // TODO: a client connected. username is empty for an anonymous one, and address
                // holds where it came from.
                break;
            case XMQ_EVENT_CLIENT_DISCONNECTED:
                // TODO: a client went, gracefully or not.
                break;
            case XMQ_EVENT_SUBSCRIBED:
            case XMQ_EVENT_UNSUBSCRIBED:
                // TODO: topic holds the filter, which may contain + and #.
                break;
            case XMQ_EVENT_PUBLISHED:
                // TODO: a message was accepted, before delivery. Only its size is here, never the
                // payload: an observer that saw every body would be on the message path, and this
                // one deliberately is not.
                break;
        }

        (void) clientId;
        (void) username;
        (void) topic;
        (void) address;
    }
'''

CPP_AUTHENTICATOR = '''
    /**
     * @brief May this client connect?
     *
     * Called on one of the broker's authentication threads, never on a message thread, so blocking
     * is expected: a directory lookup, an HTTP call, a database query all belong right here. While
     * this is outstanding the broker reads nothing more from that client and serves everybody else
     * as usual.
     *
     * Called on several of those threads at once, for different clients: anything this reads that
     * something else changes - a counter, a cache, settings a reload() replaces - has to be atomic
     * or guarded.
     *
     * Four answers, and the difference between them is what an operator will judge this on:
     *
     *   XMQ_AUTH_ALLOW           you know this client and the credentials are good.
     *   XMQ_AUTH_DENY            you know this client and they are not.
     *   XMQ_AUTH_NOT_HANDLED     "no opinion": you do not know this client. The broker asks the
     *                            next authenticator, and falls back to its own accounts if none
     *                            knew. It is the default so that installing an extension cannot
     *                            lock out clients it was never meant to judge - and it is why an
     *                            extension that always returns it does nothing at all.
     *   XMQ_AUTH_SUBSYSTEM_ERROR your store could not be reached. Not DENY, which tells a client
     *                            with perfectly good credentials that they are wrong; not
     *                            NOT_HANDLED, which hands them on and makes your outage look like
     *                            somebody else's user.
     *
     * Throwing reads as DENY, so catch what you can answer for.
     */
    xmq_auth_decision authenticate(const xmq_auth_request& request) override
    {
        const auto clientId = std::string(xmq::view(request.client_id));
        const auto username = std::string(xmq::view(request.username));
        const auto password = std::string(xmq::view(request.password));

        // TODO: decide. request also carries remote_address, protocol_version and encrypted.
        (void) clientId;
        (void) username;
        (void) password;

        return XMQ_AUTH_NOT_HANDLED;
    }
'''

CPP_AUTHORIZER = '''
    /**
     * @brief Which group is this client in?
     *
     * Asked once per connection, on the same pool as authenticate(), so it may block.
     *
     * Permissions belong to the group and never to the client. That is not a style preference: it
     * is what lets the broker cache one answer per group and topic and keep this extension off the
     * message path entirely. Return an empty string for a client you do not place: it goes into the
     * unnamed group, which authorize() is still asked about. A name longer than the broker takes
     * refuses the connection rather than being cut short.
     */
    std::string resolveGroup(const xmq_auth_request& request) override
    {
        const auto username = std::string(xmq::view(request.username));

        // TODO: which group? An account's own membership usually comes from wherever accounts live.
        (void) username;
        return {};
    }

    /**
     * @brief May this group do this to this topic?
     *
     * Asked once per group, topic and action, and then cached until the rules change - so this is
     * not on the message path, but it must not block: a connection is waiting on the answer.
     * Anything slow belongs in start(), and anything that changes belongs behind a snapshot you
     * swap - this runs on the broker's message threads, several at once.
     *
     *   XMQ_ACL_ALLOW / XMQ_ACL_DENY   the rule you found.
     *   XMQ_ACL_NOT_HANDLED            "no opinion": the next authorizer is asked, and the broker
     *                                  permits it if nobody objects. So an authorizer that always
     *                                  returns it permits everything, which is not the same as
     *                                  being switched off - it only looks the same.
     *   XMQ_ACL_SUBSYSTEM_ERROR        your store could not be reached. Refuses this one publish or
     *                                  subscribe and leaves the connection alive. Never cached.
     */
    xmq_acl_decision authorize(const std::string_view group, const std::string_view topic,
                               const xmq_acl_action action) override
    {
        // TODO: match topic against your rules for this group. Filters use + and #; a rule of '#'
        // should not hand out $SYS, so check for a '$' first if your matcher does not.
        (void) group;
        (void) topic;
        (void) action;

        return XMQ_ACL_NOT_HANDLED;
    }
'''

CPP_TAIL = '''
private:
@@MEMBERS@@};

} // namespace

// The name here must match the 'name' in xmq_extensions.conf, or the broker refuses to load this -
// otherwise the file names one extension and the broker runs another. The capability list is what
// the broker builds machinery for; declare only what is implemented above.
XMQ_DEFINE_EXTENSION(@@CLASS@@, "@@NAME@@", "1.0", @@CAPABILITY_FLAGS@@)
'''

DATABASE_INCLUDES = '''
#include <sptk5/db/AutoDatabaseConnection.h>
#include <sptk5/db/DatabaseConnectionPool.h>
#include <sptk5/db/Query.h>

#include <memory>
'''

DATABASE_START = '''
        // The SPTK that got loaded, not the header this was compiled against. A soname guards only
        // the major version, so the two can differ - and when they do the failure is a mangled name
        // or a changed structure layout, neither of which explains itself.
        if (const std::string loaded(sptk::libraryVersion()); loaded != VERSION)
        {
            log(XMQ_LOG_ERROR, "built against SPTK " + std::string(VERSION) + " but loaded SPTK " +
                                   loaded + "; rebuild this extension against the installed SPTK");
            return false;
        }

        const auto uri = setting("database");
        if (uri.empty())
        {
            log(XMQ_LOG_ERROR, "no 'database' setting");
            return false;
        }

        try
        {
            // The broker calls authenticate() from several threads at once; the pool hands each a
            // connection of its own, and the rest wait for one. The pool is not the place to
            // discover that a database has a connection limit.
            m_database = std::make_shared<sptk::DatabaseConnectionPool>(uri.c_str(), 4);

            // Asked here rather than on the first request: a wrong connection string, an absent
            // database and a schema that was never created are all configuration faults, and the
            // moment to report them is while somebody is still reading the log.
            const sptk::AutoDatabaseConnection connection(*m_database);
            // TODO: a query that proves the schema is the one you expect.
            sptk::Query probe(connection.connection(), "SELECT 1");
            probe.open();
            probe.close();
        }
        catch (const std::exception& exception)
        {
            log(XMQ_LOG_ERROR, std::string("cannot use the database: ") + exception.what());
            m_database.reset();
            return false;
        }
'''

DATABASE_STOP = '''
        m_database.reset();
'''

DATABASE_MEMBERS = '''    std::shared_ptr<sptk::DatabaseConnectionPool> m_database;
'''

CMAKE = r'''# @@NAME@@ - an XMQ extension.
#
# A plain shared library. It includes the broker's ABI headers and links nothing of the broker, so
# nothing here needs the broker's build, its compiler or its standard library.

CMAKE_MINIMUM_REQUIRED(VERSION 3.20)
PROJECT(xmq_@@IDENT@@ CXX)

SET(CMAKE_CXX_STANDARD 20)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
@@CMAKE_FIND@@
@@INSTALL_PREFIX_BLOCK@@ADD_LIBRARY(xmq_@@IDENT@@ SHARED @@CLASS@@.cpp)

# The directory holding extension/xmq_extension.h. Filled in when this project was generated; pass
# -DXMQ_EXTENSION_INCLUDE_DIR=... to build against a different broker's headers.
IF (NOT XMQ_EXTENSION_INCLUDE_DIR)
    SET(XMQ_EXTENSION_INCLUDE_DIR "@@INCLUDE_DIR@@")
ENDIF ()
IF (NOT EXISTS "${XMQ_EXTENSION_INCLUDE_DIR}/extension/xmq_extension.h")
    MESSAGE(FATAL_ERROR "No extension/xmq_extension.h under ${XMQ_EXTENSION_INCLUDE_DIR}")
ENDIF ()
TARGET_INCLUDE_DIRECTORIES(xmq_@@IDENT@@ PRIVATE "${XMQ_EXTENSION_INCLUDE_DIR}"@@CMAKE_INCLUDES@@)
@@CMAKE_LINK@@
# Hidden visibility: the one exported symbol is the entry point, and XMQ_EXTENSION_EXPORT in the
# header takes care of that one. Without this the library exports its whole implementation.
SET_TARGET_PROPERTIES(xmq_@@IDENT@@ PROPERTIES
        CXX_VISIBILITY_PRESET hidden
        VISIBILITY_INLINES_HIDDEN ON)

# Not lib/xmq: that is the directory the web interface is served from, so anything left there can be
# fetched over HTTP by anyone who can reach the control service.
INSTALL(TARGETS xmq_@@IDENT@@ LIBRARY DESTINATION lib/xmq-extensions)

# The configuration fragment, into xmq_extensions.d beside the broker's own configuration - and only
# when it is not already there. After the first install that file belongs to whoever configured this
# broker: an upgrade that overwrote it would undo their settings, "enabled": false among them, which
# is how an extension is switched off without deleting it.
#
# The 50- prefix is the order the broker reads fragments in, and the order extensions are asked in is
# part of what they mean - the broker stops at the first authenticator that answers. 50 leaves room
# on both sides.
INSTALL(CODE "
    set(fragmentDirectory \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/etc/xmq/xmq_extensions.d\")
    set(fragment \"\${fragmentDirectory}/50-@@IDENT@@.conf\")
    if (EXISTS \"\${fragment}\")
        message(STATUS \"Keeping \${fragment}\")
    else ()
        file(MAKE_DIRECTORY \"\${fragmentDirectory}\")
        file(COPY \"${CMAKE_CURRENT_SOURCE_DIR}/@@IDENT@@.conf.json\" DESTINATION \"\${fragmentDirectory}\")
        file(RENAME \"\${fragmentDirectory}/@@IDENT@@.conf.json\" \"\${fragment}\")
        message(STATUS \"Installed \${fragment}\")
    endif ()
")
'''

INSTALL_PREFIX_BLOCK = '''# Where the broker is installed, taken from where its headers were found when this project was
# generated. Without it CMake installs into /usr/local, which on most machines needs root and is not
# where this broker lives - so the library lands somewhere the broker will never be told to load it
# from. Pass -DCMAKE_INSTALL_PREFIX=... to override.
IF (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    SET(CMAKE_INSTALL_PREFIX "@@PREFIX@@" CACHE PATH "Where the broker is installed" FORCE)
ENDIF ()

'''

CMAKE_DATABASE_FIND = '''
FIND_PACKAGE(OpenSSL REQUIRED)

# SPTK, for the database layer. One implementation instead of one per database, and the same layer
# the broker itself uses. Pass -DSPTK_ROOT=... for an SPTK installed elsewhere.
FIND_PATH(SPTK_INCLUDE_DIR sptk5/sptk.h HINTS ${SPTK_ROOT}/include $ENV{HOME}/.local/include
        /usr/local/include /usr/include)
FIND_LIBRARY(SPTK_LIBRARY_CORE NAMES sputil5 HINTS ${SPTK_ROOT}/lib $ENV{HOME}/.local/lib
        /usr/local/lib /usr/lib)
FIND_LIBRARY(SPTK_LIBRARY_SPDB NAMES spdb5 HINTS ${SPTK_ROOT}/lib $ENV{HOME}/.local/lib
        /usr/local/lib /usr/lib)
IF (NOT SPTK_INCLUDE_DIR OR NOT SPTK_LIBRARY_CORE OR NOT SPTK_LIBRARY_SPDB)
    MESSAGE(FATAL_ERROR "SPTK with database support was not found; set SPTK_ROOT")
ENDIF ()
'''

CMAKE_DATABASE_LINK = '''
TARGET_LINK_LIBRARIES(xmq_@@IDENT@@ PRIVATE "${SPTK_LIBRARY_SPDB}" "${SPTK_LIBRARY_CORE}"
        OpenSSL::Crypto)
'''

CONF = '''{
  "extensions": [
    {
      "_comment": "TODO: say what this does, for whoever opens this file next.",
      "name": "@@NAME@@",
      "library": "@@LIBRARY_PATH@@",
      "enabled": true,
      "required": false,
      "settings": {@@CONF_SETTINGS@@
      }
    }
  ]
}
'''

REPO_CMAKE = '''# @@NAME@@ - an XMQ extension, built as part of this extensions repository.
#
# Two lines and no PROJECT(): the repository's own CMakeLists.txt is what the broker's build adds,
# and XMQ_ADD_EXTENSION is what keeps this isolated. It *sets* the include path and the link
# libraries rather than adding to them, so nothing the broker's directory scope carries - its
# warnings, its -fPIC, its Windows link list - reaches this. That is why an extension can live
# inside the broker's build and still see only the ABI.
@@REPO_FIND@@XMQ_ADD_EXTENSION(xmq_@@IDENT@@ SOURCES @@CLASS@@.cpp@@REPO_SPTK@@)
@@REPO_LINK@@
# Into the "extensions" install component, never the default set: built from the broker's tree this
# shares the broker's install prefix, and a plain INSTALL() would put a closed library inside the
# open broker's package. Installed deliberately, with --component extensions.
XMQ_INSTALL_EXTENSION(xmq_@@IDENT@@)
'''

REPO_DATABASE_FIND = '''
# Both found here rather than assumed. Built from the broker's tree they are already in scope and
# these do nothing; built from this repository on its own, nobody has looked for them yet - and
# XMQ_ADD_EXTENSION(... SPTK) fails without the cache variables its search fills. The guards are
# what let one file serve both builds.
IF (NOT TARGET OpenSSL::Crypto)
    FIND_PACKAGE(OpenSSL REQUIRED)
ENDIF ()

IF (NOT SPTK_INCLUDE_DIR OR NOT SPTK_LIBRARY_CORE OR NOT SPTK_LIBRARY_SPDB)
    FIND_PATH(SPTK_INCLUDE_DIR sptk5/sptk.h HINTS ${SPTK_ROOT}/include $ENV{HOME}/.local/include
            /usr/local/include /usr/include)
    FIND_LIBRARY(SPTK_LIBRARY_CORE NAMES sputil5 HINTS ${SPTK_ROOT}/lib $ENV{HOME}/.local/lib
            /usr/local/lib /usr/lib)
    FIND_LIBRARY(SPTK_LIBRARY_SPDB NAMES spdb5 HINTS ${SPTK_ROOT}/lib $ENV{HOME}/.local/lib
            /usr/local/lib /usr/lib)
    IF (NOT SPTK_INCLUDE_DIR OR NOT SPTK_LIBRARY_CORE OR NOT SPTK_LIBRARY_SPDB)
        MESSAGE(FATAL_ERROR "SPTK with database support was not found; set SPTK_ROOT")
    ENDIF ()
ENDIF ()

'''

REPO_README = '''# @@NAME@@

An XMQ extension, generated by `new-extension.py` into `@@REPO@@`.

## Build it

It is built by the broker's own build, which is the point: one IDE session, one tree, and a change
to the ABI rebuilds this with it. Configure the broker with

```sh
cmake <broker build dir> -DXMQ_EXTENSIONS_SOURCE_DIR=@@REPO@@
```

and the target `xmq_@@IDENT@@` appears beside the broker's own.

The repository also builds on its own against an installed broker - see its root `CMakeLists.txt`,
which finds the headers and `XmqExtension.cmake` under the install prefix when `XMQ_SOURCE_ROOT` is
not set.

## Let the broker load it

```sh
cmake --install <broker build dir> --component extensions
```

Named deliberately, and never part of the broker's own `cmake --install`: from the broker's tree
this shares its install prefix, and a closed library inside the open broker's package is a licensing
accident that happens silently. It lands in `lib/xmq-extensions` - **not** `lib/xmq`, which is
served over HTTP to anyone who can reach the configuration interface.

Then add the entry in `@@IDENT@@.conf.json` to `xmq_extensions.conf`, beside `xmq_server.conf`, and
restart the broker. It logs the name and version of everything it loaded, and says why for anything
it did not.

## What to write, and where

Every decision left to you is a `TODO` in `@@CLASS@@.cpp`, next to a comment saying what the choice
is between. Start with `start()`.

## The three rules

1. **Include and link nothing of the broker.** `XMQ_ADD_EXTENSION` arranges this rather than trusting
   you to remember it, which is why this file is two lines long.
2. **Declare only the capabilities you implement.** With one undeclared, the broker never builds the
   machinery behind it.
3. **Do not block the broker.** `authenticate()` and `resolveGroup()` run on a pool of their own and
   may block; `onEvent()` runs on the host's thread behind a bounded queue and may take its time;
   `authorize()` is awaited by a connection and must not block.
'''

README = '''# @@NAME@@

An XMQ extension, generated by `new-extension.py`.

## Build it

```sh
cmake -B build .
cmake --build build
```

That works before you write anything: the skeleton compiles, loads, and logs that it started. Get
that far first - it separates "my code is wrong" from "my build is wrong", and the second is much
harder to see.

## Let the broker load it

`cmake --install build` puts it in `lib/xmq-extensions` under the prefix the broker is installed
with, which is where it belongs: **not** `lib/xmq`, which is served over HTTP to anyone who can
reach the configuration interface.

The prefix was filled in when this project was generated. Without that, CMake would have used
`/usr/local`, which usually needs root and is not where this broker lives.

Then add the entry in `@@IDENT@@.conf.json` to `xmq_extensions.conf`, beside `xmq_server.conf`. The
broker has no such file until you make one, which is not an error - it just means no extensions.

Restart the broker. It logs the name and version of everything it loaded, and says why for anything
it did not.

## What to write, and where

Every decision left to you is a `TODO` in `@@CLASS@@.cpp`, next to a comment saying what the choice
is between. Start with `start()`.

## The three rules

1. **Include and link nothing of the broker.** The ABI header is the whole contract, and it is what
   lets this survive a broker upgrade and be built with another compiler.
2. **Declare only the capabilities you implement.** With one undeclared, the broker never builds the
   machinery behind it, and the path it would have sat on keeps its original shape.
3. **Do not block the broker.** `authenticate()` and `resolveGroup()` run on a pool of their own and
   may block; `onEvent()` runs on the host's thread behind a bounded queue and may take its time;
   `authorize()` is awaited by a connection and must not block.

## When it does not load

The broker's log says which. The usual causes, in the order they happen:

- *"exports no xmq_extension_describe"* - the entry point was hidden by `-fvisibility=hidden`.
  `XMQ_DEFINE_EXTENSION` applies `XMQ_EXTENSION_EXPORT` for you, so this means the macro is missing
  or is not at namespace scope.
- *"the library calls itself X"* - the name in `XMQ_DEFINE_EXTENSION` and the `name` in the
  configuration must be the same string.
- *declined* - the library was built against a newer ABI than this broker's.
'''


def write(path, text, force):
    if path.exists() and not force:
        raise SystemExit("Refusing to overwrite " + str(path) + " (use --force)")
    path.write_text(text)


def main():
    parser = argparse.ArgumentParser(
        prog="new-extension.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Create an XMQ extension project that builds and loads before a line of it is written.\n"
            "\n"
            "An extension is a shared library the broker opens at start-up. It sees one header - the\n"
            "C ABI - and links nothing of the broker, which is what lets it be built with another\n"
            "compiler, kept closed, and shipped on its own schedule.\n"
            "\n"
            "What this writes is a project with all of that already arranged. Every place where a\n"
            "decision belongs to you is marked TODO and says what the choice is between."),
        epilog=(
            "capabilities\n"
            "  One, two or all three - an extension may do more than one job. Repeat the option or\n"
            "  separate the names with commas; -c observer -c authorizer and -c observer,authorizer\n"
            "  are the same thing.\n"
            "\n"
            "  What is declared is what the broker builds machinery for, so ask for what you will\n"
            "  implement and nothing else: with a capability undeclared, the path it would have sat\n"
            "  on keeps its original shape.\n"
            "\n"
            "  observer       Watches connections, subscriptions and publishes. Told about them on a\n"
            "                 thread of the broker's own, behind a bounded queue, so it may take its\n"
            "                 time; a queue that fills drops events and counts them. It sees message\n"
            "                 sizes, never message bodies. Logging, metering, alerting.\n"
            "  authenticator  Decides whether a client may connect. Runs on a pool of its own and may\n"
            "                 block, so a directory or HTTP lookup belongs here. Answers allow, deny,\n"
            "                 no-opinion, or store-unreachable - and the difference between the last\n"
            "                 two is what an operator will judge it on.\n"
            "  authorizer     Decides what a group may publish and subscribe to. Asked once per group\n"
            "                 and topic and then cached, so it is off the message path - but a\n"
            "                 connection waits on the answer, so it must not block.\n"
            "\n"
            "what is written\n"
            "  <Class>.cpp        the extension, with a TODO at every decision\n"
            "  CMakeLists.txt     builds it against the broker's headers\n"
            "  <name>.conf.json   the entry to add to xmq_extensions.conf\n"
            "  README.md          how to build it, load it, and what not to do\n"
            "\n"
            "examples\n"
            "  new-extension.py audit-trail --capability observer\n"
            "  new-extension.py device-auth --capability authenticator --database\n"
            "  new-extension.py site-acl -c authorizer -c observer\n"
            "  new-extension.py my-ext -c observer -d ~/projects/my-ext\n"
            "\n"
            "then\n"
            "  cmake -B build . && cmake --build build\n"
            "\n"
            "  It compiles and loads as it comes out. Get that far before changing anything: it\n"
            "  separates \"my code is wrong\" from \"my build is wrong\", and the second is much\n"
            "  harder to see.\n"))

    parser.add_argument(
        "name",
        help="what the broker will call it, e.g. audit-trail. Becomes the C++ class (AuditTrail), "
             "the library (libxmq_audit_trail.so) and the name in xmq_extensions.conf, which must "
             "match or the broker refuses to load it")
    parser.add_argument(
        "--capability", "-c", action="append", metavar="WHAT", default=None,
        help="what this extension does: one, two or all three of " + ", ".join(sorted(CAPABILITIES)) +
             ". Repeat the option (-c observer -c authorizer) or separate with commas "
             "(-c observer,authorizer). Defaults to observer. See below for what each means")
    parser.add_argument(
        "--database", action="store_true",
        help="it has a store: adds SPTK's database layer and OpenSSL, a connection pool, a probe at "
             "start-up so a wrong connection string is found while somebody is reading the log, and "
             "the SPTK version check that catches a library built at a different time")
    parser.add_argument(
        "--repo", metavar="DIR",
        help="add it to an extensions repository instead of writing a standalone project: the one "
             "the broker's build takes with -DXMQ_EXTENSIONS_SOURCE_DIR. Writes <DIR>/<name> with a "
             "two-line CMakeLists, and adds the ADD_SUBDIRECTORY line to the repository's own. This "
             "is how a closed extension is built inside the broker's tree while still seeing only "
             "the ABI")
    parser.add_argument(
        "--directory", "-d", metavar="DIR",
        help="where to write the project; defaults to ./<name>, or <repo>/<name> with --repo")
    parser.add_argument(
        "--include-dir", metavar="DIR",
        help="the directory holding extension/xmq_extension.h. Defaults to where this script was "
             "installed, which is right unless you are building against another broker's headers")
    parser.add_argument(
        "--force", action="store_true",
        help="overwrite files that are already there; without it an existing file stops the run")
    arguments = parser.parse_args()

    check_name(arguments.name)

    # Both forms accepted, because both are what people type: -c a -c b and -c a,b. Order does not
    # matter and a repeat is not an error - what is declared is a set.
    capabilities = []
    for given in arguments.capability or ["observer"]:
        for one in given.split(","):
            one = one.strip()
            if not one:
                continue
            if one not in CAPABILITIES:
                raise SystemExit(
                    "Unknown capability '" + one + "'. It has to be one, two or all three of: " +
                    ", ".join(sorted(CAPABILITIES)) + ".\n"
                    "Run with --help for what each of them means.")
            if one not in capabilities:
                capabilities.append(one)

    here = pathlib.Path(__file__).resolve().parent
    # Installed as <prefix>/include/xmq/extension/new-extension.py, so the headers are found under
    # its parent; run from the broker's own tree, that parent is the tree.
    include_dir = arguments.include_dir or str(here.parent)

    # <prefix>/include/xmq is where the broker installs its ABI headers, so the prefix is two
    # directories up. Run from the broker's own source tree there is no prefix to infer, and the
    # generated project is left with CMake's default - which is right, because such a project is not
    # being installed anywhere yet.
    include_path = pathlib.Path(include_dir)
    prefix = ""
    if include_path.name == "xmq" and include_path.parent.name == "include":
        prefix = str(include_path.parent.parent)

    repo = None
    if arguments.repo:
        repo = pathlib.Path(arguments.repo).resolve()
        repo_cmake = repo / "CMakeLists.txt"
        if not repo_cmake.is_file():
            raise SystemExit("No CMakeLists.txt in " + str(repo) + ", so it is not an extensions "
                             "repository. Point --repo at the directory the broker is given with "
                             "-DXMQ_EXTENSIONS_SOURCE_DIR.")
        if "XMQ_INSTALL_EXTENSION" not in repo_cmake.read_text():
            raise SystemExit(str(repo_cmake) + " defines no XMQ_INSTALL_EXTENSION, so it is not an "
                             "extensions repository this can add to.")

    target = pathlib.Path(arguments.directory or
                          (repo / arguments.name if repo else arguments.name)).resolve()
    target.mkdir(parents=True, exist_ok=True)

    klass = class_name(arguments.name)
    ident = identifier(arguments.name)

    body = CPP_HEADER
    if "observer" in capabilities:
        body += CPP_OBSERVER
    if "authenticator" in capabilities:
        body += CPP_AUTHENTICATOR
    if "authorizer" in capabilities:
        body += CPP_AUTHORIZER
    body += CPP_TAIL

    replacements = {
        "@@CLASS@@": klass,
        "@@NAME@@": arguments.name,
        "@@IDENT@@": ident,
        "@@INCLUDE_DIR@@": include_dir,
        "@@PREFIX@@": prefix,
        "@@INSTALL_PREFIX_BLOCK@@": INSTALL_PREFIX_BLOCK if prefix else "",
        "@@CAPABILITY_FLAGS@@": " | ".join(CAPABILITIES[one] for one in sorted(capabilities)),
        "@@EXTRA_INCLUDES@@": DATABASE_INCLUDES if arguments.database else "",
        "@@START_ATTRIBUTES@@": OBSERVER_START_ATTRIBUTES if "observer" in capabilities else "",
        # An observer has nothing to answer, so it cannot be warned about answering nothing.
        "@@SKELETON_WARNING@@": (DECIDER_WARNING if capabilities != ["observer"] else OBSERVER_WARNING),
        "@@START_BODY@@": DATABASE_START if arguments.database else "",
        "@@STOP_BODY@@": DATABASE_STOP if arguments.database else "",
        "@@MEMBERS@@": DATABASE_MEMBERS if arguments.database else "",
        "@@CMAKE_FIND@@": CMAKE_DATABASE_FIND if arguments.database else "",
        "@@CMAKE_LINK@@": CMAKE_DATABASE_LINK if arguments.database else "",
        "@@CMAKE_INCLUDES@@": ' "${SPTK_INCLUDE_DIR}"' if arguments.database else "",
        "@@REPO@@": str(repo) if repo else "",
        "@@REPO_SPTK@@": " SPTK" if arguments.database else "",
        "@@REPO_FIND@@": (REPO_DATABASE_FIND if arguments.database else "\n"),
        "@@REPO_LINK@@": ("TARGET_LINK_LIBRARIES(xmq_" + ident + " PRIVATE OpenSSL::Crypto)\n"
                          if arguments.database else ""),
        # The prefix this will be installed under, so the entry is right without being edited.
        # /usr/local only when there was no prefix to infer - see the note above.
        "@@LIBRARY_PATH@@": (prefix or "/usr/local") + "/lib/xmq-extensions/libxmq_" + ident + ".so",
        "@@CONF_SETTINGS@@": ('\n        "database": "sqlite3:///var/lib/xmq/xmq_users.db",'
                              '\n        "example": "a value"' if arguments.database
                              else '\n        "example": "a value"'),
    }

    def fill(text):
        # Twice: a replacement may insert a block that carries placeholders of its own, and the
        # first pass has already gone past them.
        for _ in range(2):
            for placeholder, value in replacements.items():
                text = text.replace(placeholder, value)
        return text

    write(target / (klass + ".cpp"), fill(body), arguments.force)
    write(target / "CMakeLists.txt", fill(REPO_CMAKE if repo else CMAKE), arguments.force)
    write(target / (ident + ".conf.json"), fill(CONF), arguments.force)
    write(target / "README.md", fill(REPO_README if repo else README), arguments.force)

    added_to_repo = False
    if repo:
        # The repository's own CMakeLists is what the broker's build adds, so an extension nobody
        # named there is an extension nobody builds. Appended rather than rewritten, and only when
        # the line is not already present: this is somebody's file, not ours.
        repo_cmake = repo / "CMakeLists.txt"
        text = repo_cmake.read_text()
        line = "ADD_SUBDIRECTORY(" + arguments.name + ")"
        if line not in text:
            repo_cmake.write_text(text.rstrip("\n") + "\n" + line + "\n")
            added_to_repo = True

    written = [(klass + ".cpp", "the extension; every decision left to you is a TODO"),
               ("CMakeLists.txt", "two lines; the repository's build supplies the rest"
                                  if repo else "builds it against " + include_dir),
               (ident + ".conf.json", "the entry to add to xmq_extensions.conf"),
               ("README.md", "how to build it, load it, and what not to do")]
    widest = max(len(name) for name, _ in written)

    print("Wrote " + str(target))
    for name, what in written:
        print("  " + name.ljust(widest + 2) + what)
    print()

    if repo:
        if added_to_repo:
            print("Added to " + str(repo / "CMakeLists.txt") + ":")
            print("  ADD_SUBDIRECTORY(" + arguments.name + ")")
        else:
            print(str(repo / "CMakeLists.txt") + " already names it; left alone.")
        print()
        print("Next: configure the broker with")
        print("  -DXMQ_EXTENSIONS_SOURCE_DIR=" + str(repo))
        print("and build the target xmq_" + ident + " beside the broker's own.")
    else:
        print("Next:")
        print("  cmake -B " + str(target / "build") + " " + str(target))
        print("  cmake --build " + str(target / "build"))

    print()
    print("It compiles and loads as generated. Get that far before writing anything.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
