/**
 * @file EventLogger.cpp
 * @brief event_logger - an XMQ extension.
 *
 * Generated by new-extension.py. The TODOs are the parts that are yours; everything around them is
 * already right and can be left alone.
 *
 * Two rules that matter more than anything else here:
 *
 *  - **Nothing of the broker may be included or linked.** The C ABI is the whole contract. That is
 *    what lets this be built with a different compiler and a different standard library from the
 *    broker's, and why it keeps working when the broker is upgraded under it.
 *  - **The capability list in XMQ_DEFINE_EXTENSION is a declaration, not a description.** Declare
 *    only what this does. With a capability undeclared the broker never builds the machinery behind
 *    it - no event thread, no authentication pool - and the paths it would sit on keep their
 *    original shape.
 */

#include <extension/XmqExtension.h>

#include <mutex>
#include <string>
#include <syslog.h>

namespace {

/// The facility named in the configuration, or LOG_DAEMON. Named rather than numeric because the
/// number means nothing to whoever reads the configuration, and local0..local7 are exactly what an
/// administrator has been given to separate one service's lines from another's.
int facilityFor(const std::string& name)
{
    if (name == "user") return LOG_USER;
    if (name == "daemon" || name.empty()) return LOG_DAEMON;
    if (name == "local0") return LOG_LOCAL0;
    if (name == "local1") return LOG_LOCAL1;
    if (name == "local2") return LOG_LOCAL2;
    if (name == "local3") return LOG_LOCAL3;
    if (name == "local4") return LOG_LOCAL4;
    if (name == "local5") return LOG_LOCAL5;
    if (name == "local6") return LOG_LOCAL6;
    if (name == "local7") return LOG_LOCAL7;
    return -1;
}

/// What to call each event in the line. Written out rather than derived, because these names end up
/// in somebody's log queries and must not change when the enumeration is renumbered.
const char* eventName(const xmq_event_type type)
{
    switch (type)
    {
        case XMQ_EVENT_CLIENT_CONNECTED:    return "connected";
        case XMQ_EVENT_CLIENT_DISCONNECTED: return "disconnected";
        case XMQ_EVENT_SUBSCRIBED:          return "subscribed";
        case XMQ_EVENT_UNSUBSCRIBED:        return "unsubscribed";
        case XMQ_EVENT_PUBLISHED:           return "published";
    }
    return "unknown";
}


class EventLogger : public xmq::XmqExtensionBase
{
public:
    using XmqExtensionBase::XmqExtensionBase;

    /**
     * @brief Called once, before the broker serves anything.
     *
     * Everything expensive belongs here: connections, files, threads of your own. Returning false
     * unloads the extension; the broker still starts, unless this entry is marked 'required' in
     * xmq_extensions.conf, and then it will not serve MQTT until this starts.
     *
     * Refusing to start beats running broken. An extension that cannot do its job but answers
     * anyway looks exactly like one that works.
     */
    bool start() override
    {
        // Settings come from this extension's own block in xmq_extensions.conf and mean whatever
        // your documentation says they mean. An absent one reads as empty.
        const auto facilityName = setting("facility", "daemon");

        const auto facility = facilityFor(facilityName);
        if (facility < 0)
        {
            // Refusing to start beats guessing. A wrong facility does not fail - it writes the lines
            // somewhere nobody is looking, which is the same as not writing them and much harder to
            // notice.
            log(XMQ_LOG_ERROR, "unknown facility '" + facilityName +
                                   "'; use user, daemon, or local0..local7");
            return false;
        }

        // Held in a member, because openlog() keeps the pointer rather than copying the string: a
        // local here would leave syslog reading freed memory for the life of the process.
        m_ident = setting("ident", "xmq");

        // Facts about an event that are not fields of xmq_event travel by name. Ask here and
        // nowhere else: values are captured as the event is queued, on the broker's message
        // threads, so asking later cannot reach back for what was never taken - and only what is
        // asked for is captured, so a name nobody wants costs the broker nothing.
        //
        // This is also how an extension survives broker versions. A name this broker does not
        // publish comes back empty rather than failing, and a broker that later learns to publish
        // more names needs no new ABI and no rebuild of this.
        //
        // Where a client came from is the first thing anyone reads a connection log for, and it is
        // not a field of xmq_event - it arrives by name.
        wantEventAttributes("remote_address");

        // LOG_PID because several brokers may share a facility, and LOG_NDELAY so that a socket
        // that cannot be opened fails here rather than on the first event.
        m_facility = facility;
        openlog(m_ident.c_str(), LOG_PID | LOG_NDELAY, m_facility);
        m_open = true;

        log(XMQ_LOG_INFO, "writing broker events to syslog as '" + m_ident + "', facility " + facilityName);
        return true;
    }

    /**
     * @brief Called once, as the broker stops. Nothing else is called after it.
     */
    /**
     * @brief The settings changed while the broker runs.
     *
     * syslog is opened per process, so changing the identity or the facility means closing and
     * opening it again - and openlog() keeps the pointer it is given rather than copying it, so the
     * new identity has to be in place before the call and stay there afterwards.
     */
    bool reload() override
    {
        const auto facilityName = setting("facility", "daemon");
        const auto facility = facilityFor(facilityName);
        if (facility < 0)
        {
            // Refused rather than half-applied: the old identity is still open and still being
            // written to, which is a state that can be reasoned about.
            log(XMQ_LOG_ERROR, "unknown facility '" + facilityName + "'; keeping " + m_ident);
            return false;
        }

        const auto ident = setting("ident", "xmq");

        // onEvent() runs on its own thread meanwhile, writing through the identity this replaces -
        // and openlog() keeps a pointer into m_ident, so the string must not change under a
        // syslog() call that is reading it.
        const std::scoped_lock lock(m_syslogLock);
        if (ident == m_ident && facility == m_facility)
        {
            return true; // nothing that syslog cares about changed
        }

        if (m_open)
        {
            closelog();
        }
        m_ident = ident;
        m_facility = facility;
        openlog(m_ident.c_str(), LOG_PID | LOG_NDELAY, m_facility);
        m_open = true;

        log(XMQ_LOG_INFO, "now writing to syslog as '" + m_ident + "', facility " + facilityName);
        return true;
    }

    bool stop() override
    {
        if (m_open)
        {
            closelog();
            m_open = false;
        }

        log(XMQ_LOG_INFO, "wrote " + std::to_string(m_written) + " event(s) to syslog");
        return true;
    }

    /**
     * @brief One thing that happened in the broker.
     *
     * Runs on a thread the host keeps for this, fed by a bounded queue that the broker's reactor,
     * receive and send workers only ever push to. So taking your time here is allowed - what you
     * must not do is make the broker wait. When the queue fills, events are dropped and counted:
     * slow is lossy, never fatal.
     *
     * The strings belong to the broker and last only for this call. Copy anything you keep.
     */
    void onEvent(const xmq_event& event) override
    {
        const auto clientId = std::string(xmq::view(event.client_id));
        const auto username = std::string(xmq::view(event.username));
        const auto topic = std::string(xmq::view(event.topic));

        // Asked for in start(). Empty when the name was not requested, does not apply to this event
        // - a publish has no address - or is one this broker does not publish. All three read the
        // same way on purpose: a fact that is not there is not an error.
        const auto address = eventAttribute(event, "remote_address");

        std::string line(eventName(xmq::eventType(event)));
        line += " client=" + clientId;

        if (!username.empty())
        {
            line += " user=" + username;
        }
        if (!address.empty())
        {
            line += " from=" + std::string(address);
        }
        if (!topic.empty())
        {
            // Filter for a subscription, topic for a publish. Both may contain anything the client
            // sent, which is why the line goes to syslog as an argument and not as a format.
            line += " topic=" + topic;
        }
        if (xmq::eventType(event) == XMQ_EVENT_PUBLISHED)
        {
            line += " bytes=" + std::to_string(event.payload_size) +
                    " qos=" + std::to_string(static_cast<unsigned>(event.qos)) +
                    (event.retain != 0 ? " retained" : "");
        }

        // "%s" and never line.c_str() as the format. A client id or a topic is whatever the client
        // chose to send, and one containing %s or %n would be read as a conversion - which is a
        // stack read, or worse, driven from outside the broker.
        const std::scoped_lock lock(m_syslogLock);
        syslog(LOG_INFO, "%s", line.c_str());
        ++m_written;
    }

private:
    /// Kept for the life of the extension: openlog() stores this pointer instead of copying it.
    std::string m_ident;
    int         m_facility {LOG_DAEMON};
    bool        m_open {false};
    uint64_t    m_written {0};
    std::mutex  m_syslogLock; ///< reload() reopens syslog while onEvent() writes to it.
};

} // namespace

// The name here must match the 'name' in xmq_extensions.conf, or the broker refuses to load this -
// otherwise the file names one extension and the broker runs another. The capability list is what
// the broker builds machinery for; declare only what is implemented above.
/// What this takes. Declared so the Extensions screen can offer a form with labels and a list to
/// choose from, and refuse a wrong facility before the broker is restarted to find out.
const xmq_setting eventLoggerSettings[] {
    {.name = "ident",
     .label = "Syslog identity",
     .description = "The name syslog tags every line with; how these lines are told from another "
                    "service's on the same host",
     .type = XMQ_SETTING_STRING,
     .default_value = "xmq",
     .choices = nullptr,
     .required = 0},

    {.name = "facility",
     .label = "Syslog facility",
     .description = "Where the lines land. local0..local7 are what an administrator has to separate "
                    "one service's log from another's",
     .type = XMQ_SETTING_CHOICE,
     .default_value = "daemon",
     .choices = "user,daemon,local0,local1,local2,local3,local4,local5,local6,local7",
     .required = 0}};

XMQ_DEFINE_EXTENSION_DESCRIBED(EventLogger, "event_logger", "1.0", XMQ_CAP_OBSERVER,
                               "Writes every broker event to syslog: connections, subscriptions "
                               "and publishes, one line each",
                               eventLoggerSettings)
