#pragma once

#include "CSubscription.h"
#include "CommonHeaders.h"

namespace xmq {

/**
 * WSDL complex type class CClientSession.
 * Generated by wsdl2cxx SPTK utility.
 */
class WS_EXPORT CClientSession : public sptk::WSComplexType
{
public:

    /**
     * @brief ID of the class
     */
    static sptk::String classId()
    {
        return "ClientSession";
    }

   // Elements:
   sptk::WSString                           m_node_name {"node_name", true};
   sptk::WSString                           m_client_id {"client_id", false};
   sptk::WSString                           m_ip_address {"ip_address", true};
   sptk::WSString                           m_protocol_version {"protocol_version", false};
   sptk::WSString                           m_connected {"connected", true};
   sptk::WSArray<CSubscription>             m_subscriptions {"subscriptions"};

   /**
    * @brief Constructor.
    * @param elementName        WSDL element name.
    * @param optional           Is element optional flag.
    */
   explicit CClientSession(const char* elementName="client_session", bool optional=false);

   /**
    * @brief Copy constructor.
    * @param other              Another object.
    */
   CClientSession(const CClientSession& other);

   /**
    * @brief Move constructor.
    * @param other              Another object.
    */
   CClientSession(CClientSession&& other) noexcept;

   /**
    * @brief Destructor.
    */
   ~CClientSession() override = default;

   /**
    * @brief Copy assignment.
    * @param other              Another object.
    */
   CClientSession& operator = (const CClientSession& other) = default;

   /**
    * @brief Move assignment.
    * @param other              Another object.
    */
   CClientSession& operator = (CClientSession&& other) noexcept = default;

   /**
    * @brief Get complex type field names.
    * @param group              Field group: elements, attributes, or both.
    * @return list of fields as Strings.
    */
   static const sptk::Strings& fieldNames(sptk::WSFieldIndex::Group group);

   /**
    * @brief Check restrictions.
    * Throws an exception if any restriction is violated.
    */
   void checkRestrictions() const override;
};

}
