#pragma once

#include "CLastWill.h"
#include "CommonHeaders.h"

namespace xmq {

/**
 * WSDL complex type class CConnectMessageParameters.
 * Generated by wsdl2cxx SPTK utility.
 */
class WS_EXPORT CConnectMessageParameters : public sptk::WSComplexType
{
public:

    /**
     * @brief ID of the class
     */
    static sptk::String classId()
    {
        return "ConnectMessageParameters";
    }

   // Elements:
   sptk::WSString                           m_client_id {"client_id", false};
   sptk::WSString                           m_username {"username", false};
   sptk::WSInteger                          m_protocol_version {"protocol_version", true};
   sptk::WSBool                             m_clean_session {"clean_session", true};
   sptk::WSInteger                          m_keep_alive_sec {"keep_alive_sec", true};
   CLastWill                                m_last_will {"last_will", true};

   /**
    * @brief Constructor.
    * @param elementName        WSDL element name.
    * @param optional           Is element optional flag.
    */
   explicit CConnectMessageParameters(const char* elementName="connect_message_parameters", bool optional=false);

   /**
    * @brief Copy constructor.
    * @param other              Another object.
    */
   CConnectMessageParameters(const CConnectMessageParameters& other);

   /**
    * @brief Move constructor.
    * @param other              Another object.
    */
   CConnectMessageParameters(CConnectMessageParameters&& other) noexcept;

   /**
    * @brief Destructor.
    */
   ~CConnectMessageParameters() override = default;

   /**
    * @brief Copy assignment.
    * @param other              Another object.
    */
   CConnectMessageParameters& operator = (const CConnectMessageParameters& other) = default;

   /**
    * @brief Move assignment.
    * @param other              Another object.
    */
   CConnectMessageParameters& operator = (CConnectMessageParameters&& other) noexcept = default;

   /**
    * @brief Get complex type field names.
    * @param group              Field group: elements, attributes, or both.
    * @return list of fields as Strings.
    */
   static const sptk::Strings& fieldNames(sptk::WSFieldIndex::Group group);

   /**
    * @brief Check restrictions.
    * Throws an exception if any restriction is violated.
    */
   void checkRestrictions() const override;
};

}
