#pragma once

#include "CommonHeaders.h"

namespace xmq {

/**
 * WSDL complex type class CLastWill.
 * Generated by wsdl2cxx SPTK utility.
 */
class WS_EXPORT CLastWill : public sptk::WSComplexType
{
public:

    /**
     * @brief ID of the class
     */
    static sptk::String classId()
    {
        return "LastWill";
    }

   // Elements:

   /**
    * Last will topic
    */
   sptk::WSString                           m_topic {"topic", false};

   /**
    * Last will message
    */
   sptk::WSString                           m_message {"message", false};

   /**
    * Flag: Is the message retain?
    */
   sptk::WSBool                             m_retain {"retain", true};

   /**
    * Quality of service
    */
   sptk::WSInteger                          m_qos {"qos", true};

   /**
    * Last will delay
    */
   sptk::WSInteger                          m_will_delay {"will_delay", true};
   sptk::WSString                           m_message_properties {"message_properties", true};

   /**
    * @brief Constructor.
    * @param elementName        WSDL element name.
    * @param optional           Is element optional flag.
    */
   explicit CLastWill(const char* elementName="last_will", bool optional=false);

   /**
    * @brief Copy constructor.
    * @param other              Another object.
    */
   CLastWill(const CLastWill& other);

   /**
    * @brief Move constructor.
    * @param other              Another object.
    */
   CLastWill(CLastWill&& other) noexcept;

   /**
    * @brief Destructor.
    */
   ~CLastWill() override = default;

   /**
    * @brief Copy assignment.
    * @param other              Another object.
    */
   CLastWill& operator = (const CLastWill& other) = default;

   /**
    * @brief Move assignment.
    * @param other              Another object.
    */
   CLastWill& operator = (CLastWill&& other) noexcept = default;

   /**
    * @brief Get complex type field names.
    * @param group              Field group: elements, attributes, or both.
    * @return list of fields as Strings.
    */
   static const sptk::Strings& fieldNames(sptk::WSFieldIndex::Group group);

   /**
    * @brief Check restrictions.
    * Throws an exception if any restriction is violated.
    */
   void checkRestrictions() const override;
};

}
