IF (WIN32)
   SET (PCRE2_POSSIBLE_INCLUDE_PATHS
        $ENV{ProgramFiles}/PCRE2/include
        $ENV{ProgramFiles\(x86\)}/PCRE2/include)
   SET (PCRE2_POSSIBLE_LIB_PATHS
        $ENV{ProgramFiles}/PCRE2/lib
        $ENV{ProgramFiles\(x86\)}/PCRE2/lib)
ELSE (WIN32)
   SET (PCRE2_POSSIBLE_INCLUDE_PATHS
        $ENV{HOME}/local/include
        /usr/local/include
        /usr/include)
   SET (PCRE2_POSSIBLE_LIB_PATHS
        $ENV{HOME}/local/lib
        /usr/local/lib
        /usr/lib /usr/lib/*)
ENDIF (WIN32)

FIND_PATH(PCRE2_INCLUDE_DIR pcre2.h ${PCRE2_POSSIBLE_INCLUDE_PATHS})
FIND_LIBRARY(PCRE2_LIBRARY NAMES pcre2-8 pcre2-8-static PATHS ${PCRE2_POSSIBLE_LIB_PATHS})

IF (PCRE2_INCLUDE_DIR AND PCRE2_LIBRARY)
   SET(PCRE2_FOUND TRUE)
ENDIF (PCRE2_INCLUDE_DIR AND PCRE2_LIBRARY)

IF (PCRE2_FOUND)
   IF (NOT PCRE2_FIND_QUIETLY)
      MESSAGE(STATUS "Found PCRE2: ${PCRE2_LIBRARY}")
   ENDIF (NOT PCRE2_FIND_QUIETLY)
ELSE (PCRE2_FOUND)
   IF (PCRE2_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find PCRE2")
   ENDIF (PCRE2_FIND_REQUIRED)
ENDIF (PCRE2_FOUND)
